name=WiFiSetting
version=3.0.0
author=Nguyen Duc Tien 
maintainer=Nguyen Duc Tien <tiennd@soict.hust.edu.vn>
sentence= Platform for IoT devices connect to SIOT Data Hub
paragraph=Manage the wifi network configuration, transfer IoT data to SIOT Data Hub
category=Communication
url=https://github.com/neittien0110/ArduinoLib_WifiSetting
architectures=esp32,esp8266
includes=siot_core_lib.h
depends=WiFi,Preferences